export interface Env {
  CLOUDFLARE_R2_ACCOUNT_ID: string;
  CLOUDFLARE_R2_ACCESS_KEY_ID: string;
  CLOUDFLARE_R2_SECRET_ACCESS_KEY: string;
  CLOUDFLARE_R2_BUCKET: string;
  SUPABASE_JWT_SECRET: string;
  SUPABASE_URL?: string;
  CORS_ORIGINS?: string;
}
